Homebrew Non-deprecated Installation option
stefanhaustein/TerminalImageViewer pull request #89
Opened 2020-10-22 04:16 UTC by aaronliu0130

Option 2 is deprecated. Until macOS clang implements filesystem or we can use boost, we should use the workaround.

2020-10-22 18:58 UTC, stefanhaustein requested changes
teletype character support is required for the "-x" option only. I think it's cleaner to leave out the second change?

2020-10-23 04:25 UTC, aaronliu0130 commented
> teletype character support is required for the "-x" option only. I think it's cleaner to leave out the second change?

@stefanhaustein but I already removed that text with commit 9d0d59c!

2021-03-14 02:44 UTC, aaronliu0130 commented
@stefanhaustein

2021-03-14 10:10 UTC, merged

2021-03-14 10:11 UTC, stefanhaustein commented
Thanks for the fix and sorry for the delay!